/* Generated by the Nim Compiler v1.2.0 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var nim_program_result = 0;
var global_raise_hook_142018 = [null];
var local_raise_hook_142023 = [null];
var out_of_mem_hook_142026 = [null];
var unhandled_exception_hook_142031 = [null];
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var object_id_850031 = [0];
const electron = require('electron')
const path = require('path')
const url = require('url')
const net = require('net');

function innerHEX60gensym1260021_1265001() {
  var result_1265003 = null;

  var F={procname:"main.inner`gensym1260021",prev:framePtr,filename:"jsffi.nim",line:0};
  framePtr = F;
  BeforeRet: do {
    F.line = 430;
    var a_1265004 = null;
    F.line = 431;
    a_1265004 = {};
    F.line = 441;
    a_1265004.port = 1234;
    F.line = 450;
    result_1265003 = a_1265004;
    break BeforeRet;
  } while (false);
  framePtr = F.prev;

  return result_1265003;

}
function HEX3Aanonymous_1285007() {
  var F={procname:"main.:anonymous",prev:framePtr,filename:"main.nim",line:0};
  framePtr = F;
    console.log(("Connected to server!"));
  framePtr = F.prev;

  
}
var app_1255004 = electron.app;
var browser_window_1260004 = electron.BrowserWindow;
var main_window_1260005 = [null];
var client_1325010 = [(new net.createConnection((innerHEX60gensym1260021_1265001()), (HEX3Aanonymous_1285007)))];
function create_window_1325024() {
    function innerHEX60gensym1325031_1330001() {
      var result_1330003 = null;

      var F={procname:"createWindow.inner`gensym1325031",prev:framePtr,filename:"jsffi.nim",line:0};
      framePtr = F;
      BeforeRet: do {
        F.line = 430;
        var a_1330004 = null;
        F.line = 431;
        a_1330004 = {};
        F.line = 441;
        a_1330004.width = 800;
        F.line = 441;
        a_1330004.height = 600;
        F.line = 450;
        result_1330003 = a_1330004;
        break BeforeRet;
      } while (false);
      framePtr = F.prev;

      return result_1330003;

    }
    function innerHEX60gensym1365014_1370001() {
      var result_1370003 = null;

      var F={procname:"createWindow.inner`gensym1365014",prev:framePtr,filename:"jsffi.nim",line:0};
      framePtr = F;
      BeforeRet: do {
        F.line = 430;
        var a_1370004 = null;
        F.line = 431;
        a_1370004 = {};
        F.line = 441;
        a_1370004.pathname = ((__dirname) + "/index.html");
        F.line = 441;
        a_1370004.protocol = "file";
        F.line = 441;
        a_1370004.slashes = true;
        F.line = 450;
        result_1370003 = a_1370004;
        break BeforeRet;
      } while (false);
      framePtr = F.prev;

      return result_1370003;

    }
    function HEX3Aanonymous_1430005() {
      var F={procname:"createWindow.:anonymous",prev:framePtr,filename:"main.nim",line:0};
      framePtr = F;
        F.line = 36;
        main_window_1260005[0] = null;
      framePtr = F.prev;

      
    }

  var F={procname:"main.createWindow",prev:framePtr,filename:"main.nim",line:0};
  framePtr = F;
    F.line = 28;
    main_window_1260005[0] = (new electron.BrowserWindow((innerHEX60gensym1325031_1330001())));
    main_window_1260005[0].loadURL((url.format((innerHEX60gensym1365014_1370001()))));
    main_window_1260005[0].on(("closed"), (HEX3Aanonymous_1430005));
    client_1325010[0].write(("Hello, world\r\n"));
  framePtr = F.prev;

  
}
function HEX3Aanonymous_1525006() {
  var F={procname:"main.:anonymous",prev:framePtr,filename:"main.nim",line:0};
  framePtr = F;
    if (!(((process.platform) == "darwin"))) {
    app_1255004.quit();
    }
    
  framePtr = F.prev;

  
}
function HEX3Aanonymous_1575006() {
  var F={procname:"main.:anonymous",prev:framePtr,filename:"main.nim",line:0};
  framePtr = F;
    if ((main_window_1260005[0] == null)) {
    F.line = 51;
    create_window_1325024();
    }
    
  framePtr = F.prev;

  
}
app_1255004.on(("ready"), (create_window_1325024));
app_1255004.on(("window-all-closed"), (HEX3Aanonymous_1525006));
app_1255004.on(("activate"), (HEX3Aanonymous_1575006));
